import re

from src.agents.prompts import VISUALIZATION_AGENT_PROMPT
from src.storage.database import Database


class VisualizationAgent:
    name = "Visualization Agent"
    instructions = VISUALIZATION_AGENT_PROMPT

    def __init__(self, db: Database):
        self.db = db

    def create_mermaid(self, session_id: str, run_id: str, prompt: str, evidence: list[str]) -> str:
        title = self._short_title(prompt)
        mermaid = f"""flowchart TD
    A["User Request"] --> B["Clarify Business Goal"]
    B --> C["Gather Relevant Evidence"]
    C --> D["Analyze Process or Decision Points"]
    D --> E["{title}"]
    E --> F["Recommended Next Action"]
"""
        self.db.add_artifact(session_id, run_id, "mermaid", "Business workflow diagram", mermaid)
        self.db.add_tool_call(
            run_id,
            session_id,
            "generate_mermaid",
            {"prompt": prompt, "evidence_items": len(evidence)},
            "Generated Mermaid flowchart.",
        )
        self.db.add_step(run_id, session_id, self.name, "Generated Mermaid diagram artifact.")
        return mermaid

    def create_vega_lite(self, session_id: str, run_id: str, prompt: str, evidence: list[str]) -> dict:
        values = self._derive_business_values(evidence)
        chart_title = self._chart_title(prompt)
        spec = {
            "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
            "description": "Business KPI chart generated by the visualization agent.",
            "title": chart_title,
            "data": {"values": values},
            "mark": {"type": "bar", "tooltip": True},
            "encoding": {
                "x": {"field": "category", "type": "nominal", "title": "Category"},
                "y": {"field": "value", "type": "quantitative", "title": "Value"},
                "color": {"field": "category", "type": "nominal", "legend": None},
            },
        }
        self.db.add_artifact(session_id, run_id, "vega_lite", "Business metric chart", spec)
        self.db.add_tool_call(
            run_id,
            session_id,
            "generate_vega_lite",
            {"prompt": prompt, "evidence_items": len(evidence)},
            "Generated Vega-Lite bar chart spec.",
        )
        self.db.add_step(run_id, session_id, self.name, "Generated Vega-Lite chart artifact.")
        return spec

    def _derive_business_values(self, evidence: list[str]) -> list[dict]:
        extracted = self._extract_numeric_values(evidence)
        if extracted:
            return extracted[:12]
        if not evidence:
            return [
                {"category": "Baseline", "value": 25},
                {"category": "Current", "value": 50},
                {"category": "Target", "value": 75},
            ]
        return [
            {"category": f"Evidence {index + 1}", "value": min(100, max(5, len(text) // 20))}
            for index, text in enumerate(evidence[:6])
        ]

    def _extract_numeric_values(self, evidence: list[str]) -> list[dict]:
        values = []
        pattern = re.compile(r"([A-Za-z][A-Za-z0-9 &/%-]{2,40})\s+([$£€]?\d+(?:\.\d+)?%?)")
        for text in evidence:
            for label, raw_value in pattern.findall(text[:2000]):
                number_match = re.search(r"\d+(?:\.\d+)?", raw_value)
                if not number_match:
                    continue
                values.append({"category": label.strip()[:40], "value": float(number_match.group())})
        return values

    def _short_title(self, prompt: str) -> str:
        words = [word.strip("[](){}|\"'") for word in prompt.split()[:5]]
        return " ".join(words) or "Business Output"

    def _chart_title(self, prompt: str) -> str:
        return f"KPI view: {self._short_title(prompt)}"
